extend(photon.tokenize = tokenize, {
    TOKEN_EOF:TOKEN_EOF,
    TOKEN_OPERATOR:TOKEN_OPERATOR,
    TOKEN_EQUALITY:TOKEN_EQUALITY,
    TOKEN_RELATIONAL:TOKEN_RELATIONAL,
    TOKEN_MULTIPLICATIVE:TOKEN_MULTIPLICATIVE,
    TOKEN_ADDITIVE:TOKEN_ADDITIVE,
    TOKEN_KEYWORD:TOKEN_KEYWORD,
    TOKEN_IDENTIFIER:TOKEN_IDENTIFIER,
    TOKEN_GROUP:TOKEN_GROUP,
    TOKEN_STRING:TOKEN_STRING,
    TOKEN_NUMBER:TOKEN_NUMBER,
    TOKEN_BOOLEAN:TOKEN_BOOLEAN,
    TOKEN_NULL:TOKEN_NULL,
    TOKEN_UNDEFINED:TOKEN_UNDEFINED,
    TOKEN_DELIMITER:TOKEN_DELIMITER,
    TOKEN_WHITESPACE:TOKEN_WHITESPACE
});

photon.execFactory = execFactory;
photon.exec = execFactory(parser());