extend(photon.tokenize = tokenize, {
    TOKEN_EOF:TOKEN_EOF,
    TOKEN_OPERATOR:TOKEN_OPERATOR,
    TOKEN_KEYWORD:TOKEN_KEYWORD,
    TOKEN_IDENTIFIER:TOKEN_IDENTIFIER,
    TOKEN_GROUP:TOKEN_GROUP,
    TOKEN_STRING:TOKEN_STRING,
    TOKEN_NUMBER:TOKEN_NUMBER,
    TOKEN_BOOLEAN:TOKEN_BOOLEAN,
    TOKEN_NULL:TOKEN_NULL,
    TOKEN_DELIMITER:TOKEN_DELIMITER,
    TOKEN_WHITESPACE:TOKEN_WHITESPACE
});
